<?php

namespace Appstore\Bundle\InventoryBundle\Repository;
use Appstore\Bundle\InventoryBundle\Entity\InventoryConfig;
use Appstore\Bundle\InventoryBundle\Entity\Item;
use Appstore\Bundle\InventoryBundle\Entity\ItemPriceHistory;
use Appstore\Bundle\InventoryBundle\Entity\Purchase;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseItem;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseVendorItem;
use Appstore\Bundle\InventoryBundle\Entity\StockItem;
use Doctrine\ORM\EntityRepository;

/**
 * ItemPriceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPriceHistoryRepository extends EntityRepository
{
    public function insertItemHistoryPurchase(Purchase $purchase){

        $em = $this->_em;
        /* @var $purchaseItem PurchaseItem */
        foreach($purchase->getPurchaseItems() as $purchaseItem ) {
            $entity = new ItemPriceHistory();
            $entity->setMode('purchase');
            $entity->setItem($purchaseItem->getItem());
            $entity->setPurchasePrice($purchaseItem->getPurchasePrice());
            $entity->setSalesPrice($purchaseItem->getSalesPrice());
            $entity->setDiscountPrice($purchaseItem->getDiscountPrice());
            $em->persist($entity);
        }
        $em->flush();
    }

    public function insertPriceItemHistory(Item $item){

        $em = $this->_em;
        /* @var $item Item */
        $entity = new ItemPriceHistory();
        $entity->setMode('item');
        $entity->setItem($item);
        $entity->setPurchasePrice($item->getPurchasePrice());
        $entity->setSalesPrice($item->getSalesPrice());
        $entity->setDiscountPrice($item->getDiscountPrice());
        $em->persist($entity);
        $em->flush();
    }
}
