fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_pos:
    resource: "@PosBundle/Resources/config/routing.yml"
    prefix:   /app-pos

app_report:
    resource: "@ReportBundle/Resources/config/routing.yml"
    prefix:   /app-report

android_portal_api:
    resource: "@BinduBundle/Resources/config/apiPortal.yml"
    prefix:   /android-api-portal

android_sales_api:
    resource: "@BinduBundle/Resources/config/apiSales.yml"
    prefix:   /android-api

android_ecommerce_api:
    resource: "@BinduBundle/Resources/config/apiEcommerce.yml"
    prefix:   /android-api-ecommerce


human_resource:
    resource: "@HumanResourceBundle/Resources/config/routing.yml"
    prefix:   /human-resource

core_user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

accounting:
    resource: "@AccountingBundle/Resources/config/routing.yml"
    prefix:   /accounting

domain_user:
    resource: "@DomainUserBundle/Resources/config/routing.yml"
    prefix:   /

appstore_inventory:
    resource: "@InventoryBundle/Resources/config/routing.yml"
    prefix:   /inventory


appstore_ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /e-commerce

product_product:
    resource: "@ProductProductBundle/Resources/config/routing.yml"
    prefix:   /admin

setting_tool:
    resource: "@SettingToolBundle/Resources/config/routing.yml"
    prefix:   /

setting_content:
    resource: "@SettingContentBundle/Resources/config/routing.yml"
    prefix:   /

setting_appearance:
    resource: "@SettingAppearanceBundle/Resources/config/routing.yml"
    prefix:   /

setting_media:
    resource: "@SettingMediaBundle/Resources/config/routing.yml"
    prefix:   /

setting_location:
    resource: "@SettingLocationBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

domain_control:
    resource: "@XiideaDomainBundle/Resources/config/routing.yml"
    type:     rest

bindu:
    resource: "@BinduBundle/Resources/config/main.yml"
    prefix:   /