<?php

namespace Setting\Bundle\ToolBundle\Repository;

use Doctrine\Common\Util\Debug;
use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\MaterializedPathRepository;
use Setting\Bundle\ToolBundle\Entity\Syndicate;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileAppVersionRepository extends EntityRepository{

}
