<?php

use Appstore\Bundle\DomainUserBundle\Entity\CustomerInbox;
use Doctrine\ORM\EntityRepository;

/**
 * CustomerImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerImportRepository extends EntityRepository
{

}
